##################################################################
# Licensed Materials - Property of IBM
#  5737-I23
#  Copyright IBM Corp. 2023. All Rights Reserved.
#  U.S. Government Users Restricted Rights:
#  Use, duplication or disclosure restricted by GSA ADP Schedule
#  Contract with IBM Corp.
##################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bai-alert-sample-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bai-alert-sample-role
rules:
- apiGroups: [""] 
  resources: ["configmaps","secrets","pods"]
  verbs: ["get","list"]
- apiGroups: [""] 
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["ibmevents.ibm.com"] 
  resources: ["kafkas","kafkausers"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alert-sample
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bai-alert-sample-role
subjects:
- kind: ServiceAccount
  name: bai-alert-sample-sa